name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: make lint

    - name: Run test
      run: make tests
  
    - name: Test & publish code coverage
      uses: Aleksandr2302/frontend-project-46
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    with:
      coverageCommand: make test-coverage
     